import { RecipeModel } from './models'

export const MOCK_RECIPES: RecipeModel[] = [
    {
        id: 1,
        name: 'Lemon Herb Roasted Salmon',
        description: 'Quick, healthy and flavorful weeknight dinner with citrus and fresh herbs.',
        imgUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1400&q=80',
        isFavorite: true,
        ingredients: [
            { id: 1, name: 'Salmon fillet', quantity: 2, unit: 'each' },
            { id: 2, name: 'Lemon', quantity: 1, unit: 'each' },
            { id: 3, name: 'Olive oil', quantity: 2, unit: 'tbsp' },
            { id: 4, name: 'Garlic', quantity: 2, unit: 'cloves' },
            { id: 5, name: 'Parsley', quantity: 2, unit: 'tbsp' },
        ],
    },
    {
        id: 2,
        name: 'Avocado Toast',
        description: 'Crunchy artisan bread topped with creamy avocado and fresh seasoning.',
        imgUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1200&q=80',
        isFavorite: true,
        ingredients: [
            { id: 1, name: 'Sourdough bread', quantity: 2, unit: 'slices' },
            { id: 2, name: 'Avocado', quantity: 1, unit: 'each' },
            { id: 3, name: 'Lime juice', quantity: 1, unit: 'tsp' },
            { id: 4, name: 'Chili flakes', quantity: 1, unit: 'pinch' },
        ],
    },
    {
        id: 3,
        name: 'Spicy Thai Shrimp Curry',
        description: 'Comforting coconut curry with tender shrimp and aromatic spices.',
        imgUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1200&q=80',
        isFavorite: true,
        ingredients: [
            { id: 1, name: 'Shrimp', quantity: 300, unit: 'g' },
            { id: 2, name: 'Coconut milk', quantity: 400, unit: 'ml' },
            { id: 3, name: 'Thai curry paste', quantity: 2, unit: 'tbsp' },
            { id: 4, name: 'Bell pepper', quantity: 1, unit: 'each' },
            { id: 5, name: 'Basil', quantity: 1, unit: 'handful' },
        ],
    },
    {
        id: 4,
        name: 'Creamy Tuscan Chicken Pasta',
        description: 'Silky garlic cream sauce with chicken, spinach and sun-dried tomato.',
        imgUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?auto=format&fit=crop&w=1200&q=80',
        isFavorite: false,
        ingredients: [
            { id: 1, name: 'Pasta', quantity: 250, unit: 'g' },
            { id: 2, name: 'Chicken breast', quantity: 2, unit: 'each' },
            { id: 3, name: 'Heavy cream', quantity: 250, unit: 'ml' },
            { id: 4, name: 'Parmesan', quantity: 80, unit: 'g' },
            { id: 5, name: 'Spinach', quantity: 2, unit: 'cups' },
        ],
    },
    {
        id: 5,
        name: 'Garlic Mushroom Alfredo',
        description: 'Creamy alfredo pasta loaded with sauteed garlic mushrooms.',
        imgUrl: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?auto=format&fit=crop&w=1200&q=80',
        isFavorite: false,
        ingredients: [
            { id: 1, name: 'Fettuccine', quantity: 250, unit: 'g' },
            { id: 2, name: 'Mushrooms', quantity: 250, unit: 'g' },
            { id: 3, name: 'Garlic', quantity: 3, unit: 'cloves' },
            { id: 4, name: 'Cream', quantity: 200, unit: 'ml' },
            { id: 5, name: 'Parmesan', quantity: 60, unit: 'g' },
        ],
    },
    {
        id: 6,
        name: 'Creamy Coconut Bean Curry',
        description: 'Rich coconut curry with tender beans and warming spices.',
        imgUrl: 'https://images.unsplash.com/photo-1631292784640-2b24be784d5d?auto=format&fit=crop&w=1200&q=80',
        isFavorite: true,
        ingredients: [
            { id: 1, name: 'White beans', quantity: 350, unit: 'g' },
            { id: 2, name: 'Coconut milk', quantity: 300, unit: 'ml' },
            { id: 3, name: 'Onion', quantity: 1, unit: 'each' },
            { id: 4, name: 'Curry powder', quantity: 2, unit: 'tsp' },
            { id: 5, name: 'Cilantro', quantity: 1, unit: 'handful' },
        ],
    },
    {
        id: 7,
        name: 'Vegan Black Bean Burger',
        description: 'Smoky plant-based burger with black bean patty and crisp toppings.',
        imgUrl: 'https://images.unsplash.com/photo-1525059696034-4967a729002e?auto=format&fit=crop&w=1200&q=80',
        isFavorite: false,
        ingredients: [
            { id: 1, name: 'Black beans', quantity: 400, unit: 'g' },
            { id: 2, name: 'Breadcrumbs', quantity: 80, unit: 'g' },
            { id: 3, name: 'Onion', quantity: 1, unit: 'each' },
            { id: 4, name: 'Burger buns', quantity: 4, unit: 'each' },
            { id: 5, name: 'Lettuce', quantity: 4, unit: 'leaves' },
        ],
    },
    {
        id: 8,
        name: 'Mediterranean Grain Bowl',
        description: 'Fresh grains, roasted vegetables and bright lemon tahini sauce.',
        imgUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80',
        isFavorite: false,
        ingredients: [
            { id: 1, name: 'Quinoa', quantity: 180, unit: 'g' },
            { id: 2, name: 'Chickpeas', quantity: 200, unit: 'g' },
            { id: 3, name: 'Cucumber', quantity: 1, unit: 'each' },
            { id: 4, name: 'Cherry tomatoes', quantity: 200, unit: 'g' },
            { id: 5, name: 'Tahini', quantity: 2, unit: 'tbsp' },
        ],
    }
];