import { RecipeModel } from './models'

export const MOCK_RECIPES: RecipeModel[] = [
    {
        id: 1,
        name: 'Lemon-Garlic Shrimp Pasta',
        description: 'Silky garlic butter pasta tossed with shrimp, lemon zest and fresh herbs.',
        imgUrl: 'https://images.unsplash.com/photo-1563379091339-03246963d29a?auto=format&fit=crop&w=1200&q=80',
        isFavorite: true,
        ingredients: [
            { id: 1, name: 'Shrimp', quantity: 250, unit: 'g' },
            { id: 2, name: 'Lemon', quantity: 1, unit: 'each' },
            { id: 3, name: 'Pasta', quantity: 250, unit: 'g' },
            { id: 4, name: 'Garlic', quantity: 2, unit: 'cloves' },
            { id: 5, name: 'Parsley', quantity: 2, unit: 'tbsp' },
        ],
        durationMinutes: 35,
        difficulty: 'Easy',
        rating: 4.8,
        reviewCount: 1200,
        steps: [
            'Cook pasta according to package directions until al dente. Drain and reserve ½ cup pasta water.',
            'Sauté shrimp in olive oil and garlic butter until pink, about 2–3 minutes per side. Remove and set aside.',
            'Combine pasta with lemon juice, zest, reserved water and shrimp. Toss until silky and well coated.',
        ],
        tips: 'Use fresh lemon juice and zest for the brightest flavor. Pull shrimp off heat when just pink — they continue cooking from residual heat.',
    },
    {
        id: 2,
        name: 'Mediterranean Quinoa Salad',
        description: 'A bright grain salad with cucumber, tomato, herbs and creamy feta.',
        imgUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80',
        isFavorite: true,
        ingredients: [
            { id: 1, name: 'Quinoa', quantity: 180, unit: 'g' },
            { id: 2, name: 'Tomatoes', quantity: 150, unit: 'g' },
            { id: 3, name: 'Cucumber', quantity: 1, unit: 'each' },
            { id: 4, name: 'Feta', quantity: 60, unit: 'g' },
        ],
        durationMinutes: 35,
        difficulty: 'Easy',
        rating: 4.8,
        reviewCount: 1100,
        steps: [
            'Rinse and cook quinoa in salted water until fluffy. Spread on a tray to cool.',
            'Dice tomatoes, cucumber and red onion. Crumble feta cheese.',
            'Toss everything with olive oil, lemon juice, salt and fresh herbs.',
        ],
        tips: 'Make ahead and refrigerate — the flavors develop and get even better overnight.',
    },
    {
        id: 3,
        name: 'Roasted Veggie Buddha Bowl',
        description: 'Oven-roasted vegetables, grains and creamy dressing in a hearty bowl.',
        imgUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80',
        isFavorite: true,
        ingredients: [
            { id: 1, name: 'Broccoli', quantity: 180, unit: 'g' },
            { id: 2, name: 'Sweet potato', quantity: 250, unit: 'g' },
            { id: 3, name: 'Rice', quantity: 180, unit: 'g' },
            { id: 4, name: 'Chickpeas', quantity: 150, unit: 'g' },
            { id: 5, name: 'Tahini', quantity: 2, unit: 'tbsp' },
        ],
        durationMinutes: 35,
        difficulty: 'Medium',
        rating: 4.8,
        reviewCount: 1200,
        steps: [
            'Preheat oven to 200°C. Toss sweet potato and broccoli with oil, salt and spices.',
            'Roast vegetables for 25–30 minutes until golden and tender.',
            'Assemble bowls with rice, roasted vegetables, chickpeas and tahini drizzle.',
        ],
        tips: 'Massage kale with a little oil and salt if adding greens — it softens the texture beautifully.',
    },
    {
        id: 4,
        name: 'New York Steak',
        description: 'Seared steakhouse-style with buttered green beans and pan sauce.',
        imgUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
        isFavorite: false,
        ingredients: [
            { id: 1, name: 'Steak', quantity: 1, unit: 'each' },
            { id: 2, name: 'Green beans', quantity: 180, unit: 'g' },
            { id: 3, name: 'Butter', quantity: 1, unit: 'tbsp' },
            { id: 4, name: 'Garlic', quantity: 2, unit: 'cloves' },
            { id: 5, name: 'Rosemary', quantity: 1, unit: 'sprig' },
        ],
        durationMinutes: 35,
        difficulty: 'Easy',
        rating: 4.8,
        reviewCount: 1200,
        steps: [
            'Bring steak to room temperature. Season generously with salt and pepper.',
            'Sear in a hot cast-iron skillet with oil for 3–4 minutes each side. Add butter, garlic and rosemary to baste.',
            'Rest steak for 5 minutes before slicing. Serve with buttered green beans.',
        ],
        tips: 'Let the steak rest — this redistributes juices for a more tender, flavorful bite.',
    },
    {
        id: 5,
        name: 'Thai Green Curry Chicken',
        description: 'Creamy coconut curry with chicken, herbs and bright green vegetables.',
        imgUrl: 'https://images.unsplash.com/photo-1562967916-eb82221dfb92?auto=format&fit=crop&w=1200&q=80',
        isFavorite: false,
        ingredients: [
            { id: 1, name: 'Chicken', quantity: 250, unit: 'g' },
            { id: 2, name: 'Coconut milk', quantity: 400, unit: 'ml' },
            { id: 3, name: 'Green curry paste', quantity: 2, unit: 'tbsp' },
            { id: 4, name: 'Basil', quantity: 1, unit: 'handful' },
            { id: 5, name: 'Rice', quantity: 180, unit: 'g' },
        ],
        durationMinutes: 35,
        difficulty: 'Medium',
        rating: 4.8,
        reviewCount: 1200,
        steps: [
            'Slice chicken and vegetables. Heat oil in a deep pan over medium-high heat.',
            'Fry curry paste for 1 minute, then add coconut milk and bring to a simmer.',
            'Add chicken and vegetables. Cook until done and sauce thickens. Finish with fresh basil.',
        ],
        tips: 'Toast the curry paste in oil before adding coconut milk — it deepens the flavor significantly.',
    },
    {
        id: 6,
        name: 'Roasted Bowl',
        description: 'A warm bowl layered with roasted vegetables, grains and tender protein.',
        imgUrl: 'https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?auto=format&fit=crop&w=1200&q=80',
        isFavorite: true,
        ingredients: [
            { id: 1, name: 'Chicken', quantity: 200, unit: 'g' },
            { id: 2, name: 'Broccoli', quantity: 150, unit: 'g' },
            { id: 3, name: 'Rice', quantity: 180, unit: 'g' },
            { id: 4, name: 'Carrot', quantity: 1, unit: 'each' },
            { id: 5, name: 'Sesame', quantity: 1, unit: 'tbsp' },
        ],
        durationMinutes: 35,
        difficulty: 'Easy',
        rating: 4.8,
        reviewCount: 1200,
    },
    {
        id: 7,
        name: 'Roasted Veggie',
        description: 'Pan-finished noodles with colorful roasted vegetables and savory sauce.',
        imgUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=80',
        isFavorite: false,
        ingredients: [
            { id: 1, name: 'Pasta', quantity: 220, unit: 'g' },
            { id: 2, name: 'Broccoli', quantity: 120, unit: 'g' },
            { id: 3, name: 'Bell pepper', quantity: 1, unit: 'each' },
            { id: 4, name: 'Mushrooms', quantity: 150, unit: 'g' },
            { id: 5, name: 'Soy sauce', quantity: 2, unit: 'tbsp' },
        ],
        durationMinutes: 30,
        difficulty: 'Easy',
        rating: 4.8,
        reviewCount: 2000,
    },
    {
        id: 8,
        name: 'Chicken Baster',
        description: 'Juicy skillet chicken finished with herbs and roasted vegetables.',
        imgUrl: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=1200&q=80',
        isFavorite: false,
        ingredients: [
            { id: 1, name: 'Chicken', quantity: 220, unit: 'g' },
            { id: 2, name: 'Potatoes', quantity: 250, unit: 'g' },
            { id: 3, name: 'Garlic', quantity: 2, unit: 'cloves' },
            { id: 4, name: 'Broccoli', quantity: 140, unit: 'g' },
            { id: 5, name: 'Butter', quantity: 1, unit: 'tbsp' },
        ],
        durationMinutes: 35,
        difficulty: 'Easy',
        rating: 4.8,
        reviewCount: 2000,
    },
    {
        id: 9,
        name: 'Creamy Tuscan',
        description: 'Creamy pasta with chicken, herbs and a rich garlic parmesan finish.',
        imgUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?auto=format&fit=crop&w=1200&q=80',
        isFavorite: false,
        ingredients: [
            { id: 1, name: 'Chicken', quantity: 200, unit: 'g' },
            { id: 2, name: 'Pasta', quantity: 220, unit: 'g' },
            { id: 3, name: 'Cream', quantity: 200, unit: 'ml' },
            { id: 4, name: 'Parmesan', quantity: 60, unit: 'g' },
            { id: 5, name: 'Spinach', quantity: 80, unit: 'g' },
        ],
        durationMinutes: 35,
        difficulty: 'Easy',
        rating: 4.8,
        reviewCount: 1200,
    },
    {
        id: 10,
        name: 'Thai Green Curry Chicken',
        description: 'Fragrant curry broth with shrimp, basil and silky coconut richness.',
        imgUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1200&q=80',
        isFavorite: true,
        ingredients: [
            { id: 1, name: 'Shrimp', quantity: 250, unit: 'g' },
            { id: 2, name: 'Coconut milk', quantity: 350, unit: 'ml' },
            { id: 3, name: 'Basil', quantity: 1, unit: 'handful' },
            { id: 4, name: 'Lime', quantity: 1, unit: 'each' },
            { id: 5, name: 'Rice', quantity: 180, unit: 'g' },
        ],
        durationMinutes: 35,
        difficulty: 'Medium',
        rating: 4.8,
        reviewCount: 1200,
    }
];