import { Recipe } from './models';

export const MOCK_RECIPES: Recipe[] = [
  {
    id: 'recipe-001',
    title: 'Lemon Herb Roasted Salmon',
    description: 'Quick, healthy and flavorful weeknight dinner with citrus and fresh herbs.',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1400&q=80',
    category: 'Seafood',
    tags: ['healthy', 'quick', 'gluten-free', 'pescatarian'],
    isFavorite: true,
    ingredients: [
      { id: 1, name: 'Salmon fillet', quantity: 2, unit: 'each' },
      { id: 2, name: 'Lemon', quantity: 1, unit: 'each' },
      { id: 3, name: 'Olive oil', quantity: 2, unit: 'tbsp' },
      { id: 4, name: 'Garlic', quantity: 2, unit: 'cloves' },
      { id: 5, name: 'Parsley', quantity: 2, unit: 'tbsp' },
    ],
    steps: [
      { order: 1, instruction: 'Preheat the oven to 200°C (400°F) and line a baking sheet with parchment paper.' },
      { order: 2, instruction: 'Pat the salmon fillets dry and place them skin-side down on the baking sheet.' },
      { order: 3, instruction: 'Mix olive oil, minced garlic, lemon zest and chopped parsley; brush evenly over the salmon.' },
      { order: 4, instruction: 'Bake for 12–15 minutes until the salmon flakes easily. Finish with a squeeze of fresh lemon juice before serving.' },
    ],
    meta: { duration: 25, difficulty: 'easy', rating: 4.9, reviewsCount: 2400, calories: 380 },
  },
  {
    id: 'recipe-002',
    title: 'Avocado Toast',
    description: 'Crunchy artisan bread topped with creamy avocado and fresh seasoning.',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1200&q=80',
    category: 'Breakfast',
    tags: ['vegetarian', 'quick', 'vegan', 'breakfast'],
    isFavorite: true,
    ingredients: [
      { id: 1, name: 'Sourdough bread', quantity: 2, unit: 'slices' },
      { id: 2, name: 'Avocado', quantity: 1, unit: 'each' },
      { id: 3, name: 'Lime juice', quantity: 1, unit: 'tsp' },
      { id: 4, name: 'Chili flakes', quantity: 1, unit: 'pinch' },
    ],
    steps: [
      { order: 1, instruction: 'Toast the sourdough slices in a toaster or under the grill until golden and crisp.' },
      { order: 2, instruction: 'Halve the avocado, remove the pit, and scoop the flesh into a bowl.' },
      { order: 3, instruction: 'Mash the avocado with lime juice, a pinch of salt, and chili flakes to taste.' },
      { order: 4, instruction: 'Spread the mixture generously over each toast slice. Season and serve immediately.' },
    ],
    meta: { duration: 10, difficulty: 'easy', rating: 4.8, reviewsCount: 1200, calories: 280 },
  },
  {
    id: 'recipe-003',
    title: 'Spicy Thai Shrimp Curry',
    description: 'Comforting coconut curry with tender shrimp and aromatic spices.',
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1200&q=80',
    category: 'Asian',
    tags: ['spicy', 'seafood', 'gluten-free', 'dairy-free'],
    isFavorite: true,
    ingredients: [
      { id: 1, name: 'Shrimp', quantity: 300, unit: 'g' },
      { id: 2, name: 'Coconut milk', quantity: 400, unit: 'ml' },
      { id: 3, name: 'Thai curry paste', quantity: 2, unit: 'tbsp' },
      { id: 4, name: 'Bell pepper', quantity: 1, unit: 'each' },
      { id: 5, name: 'Basil', quantity: 1, unit: 'handful' },
    ],
    steps: [
      { order: 1, instruction: 'Heat a large pan over medium-high heat and add a splash of oil.' },
      { order: 2, instruction: 'Fry the Thai curry paste for 1–2 minutes until fragrant and deepened in color.' },
      { order: 3, instruction: 'Add the sliced bell pepper and stir-fry for 2 minutes until slightly softened.' },
      { order: 4, instruction: 'Pour in the coconut milk and bring to a gentle simmer for 5 minutes.' },
      { order: 5, instruction: 'Add the shrimp and cook for 3–4 minutes until pink and opaque. Finish with fresh basil and serve over jasmine rice.' },
    ],
    meta: { duration: 30, difficulty: 'medium', rating: 4.8, reviewsCount: 1100, calories: 420 },
  },
  {
    id: 'recipe-004',
    title: 'Creamy Tuscan Chicken Pasta',
    description: 'Silky garlic cream sauce with chicken, spinach and sun-dried tomato.',
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?auto=format&fit=crop&w=1200&q=80',
    category: 'Pasta',
    tags: ['comfort-food', 'creamy', 'chicken'],
    isFavorite: false,
    ingredients: [
      { id: 1, name: 'Pasta', quantity: 250, unit: 'g' },
      { id: 2, name: 'Chicken breast', quantity: 2, unit: 'each' },
      { id: 3, name: 'Heavy cream', quantity: 250, unit: 'ml' },
      { id: 4, name: 'Parmesan', quantity: 80, unit: 'g' },
      { id: 5, name: 'Spinach', quantity: 2, unit: 'cups' },
    ],
    steps: [
      { order: 1, instruction: 'Cook pasta in generously salted boiling water until al dente; reserve ½ cup pasta water, then drain.' },
      { order: 2, instruction: 'Season the chicken breasts with salt and pepper; sear in olive oil until golden on both sides. Slice into strips.' },
      { order: 3, instruction: 'In the same pan, sauté minced garlic for 30 seconds, then pour in the heavy cream and simmer for 3 minutes.' },
      { order: 4, instruction: 'Stir in grated parmesan and fresh spinach until wilted. Add the chicken strips and combine.' },
      { order: 5, instruction: 'Toss with cooked pasta, adding pasta water as needed to achieve a silky sauce. Serve hot.' },
    ],
    meta: { duration: 35, difficulty: 'medium', rating: 4.7, reviewsCount: 1000, calories: 580 },
  },
  {
    id: 'recipe-005',
    title: 'Garlic Mushroom Alfredo',
    description: 'Creamy alfredo pasta loaded with sauteed garlic mushrooms.',
    imageUrl: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?auto=format&fit=crop&w=1200&q=80',
    category: 'Pasta',
    tags: ['vegetarian', 'creamy', 'comfort-food'],
    isFavorite: false,
    ingredients: [
      { id: 1, name: 'Fettuccine', quantity: 250, unit: 'g' },
      { id: 2, name: 'Mushrooms', quantity: 250, unit: 'g' },
      { id: 3, name: 'Garlic', quantity: 3, unit: 'cloves' },
      { id: 4, name: 'Cream', quantity: 200, unit: 'ml' },
      { id: 5, name: 'Parmesan', quantity: 60, unit: 'g' },
    ],
    steps: [
      { order: 1, instruction: 'Boil fettuccine according to package instructions until al dente; save ½ cup pasta water before draining.' },
      { order: 2, instruction: 'In a large skillet over medium-high heat, melt butter and sauté sliced mushrooms with minced garlic until golden.' },
      { order: 3, instruction: 'Reduce heat, pour in the cream, and simmer for 4–5 minutes until slightly thickened.' },
      { order: 4, instruction: 'Stir in grated parmesan, season to taste, then toss with fettuccine. Use pasta water to loosen if needed.' },
    ],
    meta: { duration: 30, difficulty: 'easy', rating: 4.8, reviewsCount: 1300, calories: 520 },
  },
  {
    id: 'recipe-006',
    title: 'Creamy Coconut Bean Curry',
    description: 'Rich coconut curry with tender beans and warming spices.',
    imageUrl: 'https://images.unsplash.com/photo-1631292784640-2b24be784d5d?auto=format&fit=crop&w=1200&q=80',
    category: 'Vegan',
    tags: ['vegan', 'gluten-free', 'high-protein', 'dairy-free'],
    isFavorite: true,
    ingredients: [
      { id: 1, name: 'White beans', quantity: 350, unit: 'g' },
      { id: 2, name: 'Coconut milk', quantity: 300, unit: 'ml' },
      { id: 3, name: 'Onion', quantity: 1, unit: 'each' },
      { id: 4, name: 'Curry powder', quantity: 2, unit: 'tsp' },
      { id: 5, name: 'Cilantro', quantity: 1, unit: 'handful' },
    ],
    steps: [
      { order: 1, instruction: 'Dice the onion and sauté in oil over medium heat for 5 minutes until soft and translucent.' },
      { order: 2, instruction: 'Add curry powder and stir for 1 minute to bloom the spices in the oil.' },
      { order: 3, instruction: 'Pour in the coconut milk and add the drained white beans. Stir to combine.' },
      { order: 4, instruction: 'Simmer for 15 minutes, season to taste, and serve topped with fresh cilantro alongside steamed rice.' },
    ],
    meta: { duration: 35, difficulty: 'easy', rating: 4.8, reviewsCount: 1200, calories: 340 },
  },
  {
    id: 'recipe-007',
    title: 'Vegan Black Bean Burger',
    description: 'Smoky plant-based burger with black bean patty and crisp toppings.',
    imageUrl: 'https://images.unsplash.com/photo-1525059696034-4967a729002e?auto=format&fit=crop&w=1200&q=80',
    category: 'Vegan',
    tags: ['vegan', 'high-protein', 'comfort-food'],
    isFavorite: false,
    ingredients: [
      { id: 1, name: 'Black beans', quantity: 400, unit: 'g' },
      { id: 2, name: 'Breadcrumbs', quantity: 80, unit: 'g' },
      { id: 3, name: 'Onion', quantity: 1, unit: 'each' },
      { id: 4, name: 'Burger buns', quantity: 4, unit: 'each' },
      { id: 5, name: 'Lettuce', quantity: 4, unit: 'leaves' },
    ],
    steps: [
      { order: 1, instruction: 'Drain and rinse the black beans, then mash roughly in a large bowl, leaving some texture.' },
      { order: 2, instruction: 'Finely dice the onion and sauté in oil until soft; add to the mashed beans.' },
      { order: 3, instruction: 'Mix in breadcrumbs and seasoning until the mixture holds together. Divide and shape into 4 patties.' },
      { order: 4, instruction: 'Pan-fry or grill the patties for 4–5 minutes per side over medium heat until a golden crust forms.' },
      { order: 5, instruction: 'Toast the buns, then assemble with lettuce, the patty, and your preferred toppings. Serve immediately.' },
    ],
    meta: { duration: 35, difficulty: 'medium', rating: 4.8, reviewsCount: 1200, calories: 460 },
  },
  {
    id: 'recipe-008',
    title: 'Mediterranean Grain Bowl',
    description: 'Fresh grains, roasted vegetables and bright lemon tahini sauce.',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80',
    category: 'Salads',
    tags: ['vegetarian', 'healthy', 'gluten-free', 'meal-prep'],
    isFavorite: false,
    ingredients: [
      { id: 1, name: 'Quinoa', quantity: 180, unit: 'g' },
      { id: 2, name: 'Chickpeas', quantity: 200, unit: 'g' },
      { id: 3, name: 'Cucumber', quantity: 1, unit: 'each' },
      { id: 4, name: 'Cherry tomatoes', quantity: 200, unit: 'g' },
      { id: 5, name: 'Tahini', quantity: 2, unit: 'tbsp' },
    ],
    steps: [
      { order: 1, instruction: 'Rinse quinoa under cold water and cook in salted water per package instructions; fluff with a fork and cool slightly.' },
      { order: 2, instruction: 'Drain and rinse chickpeas; toss with olive oil, cumin and salt. Spread on a baking sheet and roast at 200°C for 20 minutes until crispy.' },
      { order: 3, instruction: 'Dice the cucumber and halve the cherry tomatoes.' },
      { order: 4, instruction: 'Whisk tahini with lemon juice, garlic, and 2–3 tablespoons of water until smooth. Assemble the bowls and drizzle with tahini dressing.' },
    ],
    meta: { duration: 25, difficulty: 'easy', rating: 4.6, reviewsCount: 860, calories: 390 },
  },
];